import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import "./globals.css";


// app/layout.tsx or wherever your layout is defined
const poppins = Poppins({
  subsets: ['latin'],
  weight: '500',         // Normal weight
  style: 'italic',       // Italic style
  display: 'swap',
  variable: '--font-poppins',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
